### PR TITLE
Move to cssbeautifier and fix delays in category scraping

### LINKED ISSUE #151: css-beautify has been removed
The scrapper uses `css-beautify` as Python dependency.

It cannot be found anymore in PyPi, and [this page](https://libraries.io/pypi/css-beautify) states that it has been removed, I did not found any other information on the web.

We need a replacement.

### LINKED ISSUE #157: Category scraping in not honouring the configured `delay`
When scraping category content, the scraper does not respect the configured `delay` between website requests.

This obviously poses throttling issues.

### PR DESCRIPTION
**Pull request by benoit74**
Fix #151 
Fix #157

## Changes
- Migrate from `css-beautify` to `cssbeautifier`
  - Fix in-line CSS `data` which was not detected correctly anymore 
- Add missing delay in category scraping and fix delay between pages

### CODE REVIEW

**Comment by benoit74** [comment]
I'm not sure it will be a big game changer, but combined with pywikiapi changes, it will anyway enhance the situation.

**Review by rgaudin — APPROVED** [review]
Hard to say anything at the moment

**Comment by rgaudin** [comment]
We all those “small bugs” we'll need more meaningful PR names 😉

**Comment by benoit74** [comment]
Looks like I might have forgotten to update the issue title 🤪

**Pull request merged**
